// <auto-generated />
namespace Udemy_VidlyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MemberShipType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberShipType));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131256411_MemberShipType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
